### ISSUE TITLE
Support for MacOS Arm

### ISSUE THREAD

**Issue by Nicholaswogan** [conda-forge/scikits.odes-feedstock#15] opened 2022-10-07 03:02 UTC
### Comment:

Can you please add binaries for MacOS Arm? Thanks!

**Comment by moorepants** [comment] 2022-10-15 07:50
I don't see an auto PR from conda forge, so my guess is that a dependency still has to be built for this new platform.

**Comment by moorepants** [comment] 2022-10-15 07:52
It may be because we have:
https://github.com/conda-forge/scikits.odes-feedstock/blob/main/recipe/meta.yaml#L31

Until scikits.odes supports sundials > 6, then I don't think this can be fixed here. Open an issue on scikits.odes requesting support for sundials 6.

**Comment by moorepants** [comment] 2024-01-18 12:09
scikits.odes https://github.com/bmcage/odes/releases/tag/v2.7.0 supports sundials 6.

**Comment by c-randall** [comment] 2024-07-03 00:10
Can someone give an update on this thread? My new package builds and tests well on linux and windows machines but it is not able to be built or tested on macs with arm64 since the scikits.odes dependency cannot be installed.

**Comment by moorepants** [comment] 2024-07-03 03:21
There is an attempt here: https://github.com/conda-forge/scikits.odes-feedstock/pull/23. You are welcome to get that PR working.

**Comment by c-randall** [comment] 2024-07-03 23:31
Thanks for the reply. This definitely isn't my area of expertise, so I'll have to wait for someone else to keep digging into it. In the meantime, I found a workaround that people might be interested in. The original post was on [stackoverflow](https://stackoverflow.com/questions/71515117/how-to-set-up-a-conda-osx-64-environment-on-arm-mac).

The quick summary is that you can use `conda config --env --set subdir osx-64` to set an individual environment's architecture to use x86 binaries. I tested this in my CI using `macos-latest` and was able to get my passing tests, for now.

**Comment by moorepants** [comment] 2024-07-04 03:16
If you are using github actions you can also set to macos-13 (or 12) and it is the old runners with intel chips.

**Comment by c-randall** [comment] 2024-08-12 23:08
I was able to get the arm64 builds working. I just submitted a [PR](https://github.com/conda-forge/scikits.odes-feedstock/pull/24). The issue was that the bot added `cython` to the build step, but it wasn't limited to a version <3, which is required for `scikits.odes.sundials`. You can see all builds are successful in the PR. I started with the bot's branch and made two changes on top of its commits:
1) Restrict `cython <3` during the build
2) Increase the build number to 3

The [issue #147](https://github.com/bmcage/odes/issues/147) you mentioned in the bot's PR is still real and affects the `lapack` linear solvers. This will need to be fixed in the source code, but was not the cause of the failing builds here.

**Closed as completed** 2024-08-13 03:24 UTC
Labels: question
